Task/270 database documentation
therossee/ThesisManagement-Group09 pull request #143
Opened 2024-01-13 09:14 UTC by DianaHus

- Added db documentation in the readme.md file
- Db change in thesisProposal table: capital letter for type field and required_knowledge longer text

2024-01-13 11:53 UTC, Sylvie-Molinatto requested changes
Missing tables and there is something to discuss in today meeting

2024-01-14 18:03 UTC, Sylvie-Molinatto requested changes
The db documentation should be in a README.md file which is shown by github by default, moreover there is an error in the general README.md file (not 'documentation' folder but 'database' folder

2024-01-15 07:45 UTC, DianaHus commented
Per ora il link nel README.md generale non funziona, ma è fatto apposta perché funzioni nel main

2024-01-15 08:43 UTC, Sylvie-Molinatto approved these changes

2024-01-15 08:44 UTC, merged